
"""Revised sparse-data trainer for the Re=3900 transient cylinder wake.

Key corrections relative to the legacy benchmark_train.py
-----------------------------------------------------------
1. `supervised_ratio` selects a genuinely sparse nested supervised set from the
   fixed protocol; it is NOT a batch-size fraction.
2. Data batch size and equation batch size are explicit, independent arguments.
3. Fixed validation and held-out test sets are read from the protocol.
4. Held-out test data are NEVER used during training or hyperparameter selection.
5. All comparable physics-constrained methods read exactly the same collocation
   point file generated by the protocol.
6. Backbone, additional trainable parameters, and total optimized parameters are
   reported separately.
7. Checkpoints and logs are written under a user-specified results root rather
   than the legacy global benchmark_results directory.

This script is intended first for smoke tests and physics-weight selection.
Formal held-out testing is performed only after hyperparameters are fixed.
"""

from __future__ import annotations

import argparse
import math
import time
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import pandas as pd
import torch

from benchmark_config import (
    DEFAULT_TRAINING,
    LAYER_MAT_PSI,
    METHODS,
    REYNOLDS,
)
from benchmark_tools import build_model, count_parameters, get_device, set_seed
from pinn_model import read_2D_data

try:
    from learning_schdule import ChainedScheduler
except ImportError:
    from learning_schedule import ChainedScheduler


ALLOWED_RATIOS = (0.01, 0.02, 0.03, 0.04, 0.05)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Train cylinder PINNs with the corrected nested sparse-data protocol."
    )
    p.add_argument(
        "--data-path",
        default="./2d_cylinder_Re3900_100x100_kw_sst.mat",
    )
    p.add_argument(
        "--protocol-root",
        default="./results_cylinder_protocol_v1_1/protocol",
    )
    p.add_argument(
        "--results-root",
        default="./results_cylinder_v2",
    )
    p.add_argument(
        "--method",
        default="standard_pinn",
        choices=list(METHODS.keys()),
    )
    p.add_argument("--epochs", type=int, default=DEFAULT_TRAINING["epochs"])
    p.add_argument("--supervised-ratio", type=float, default=0.02)
    p.add_argument("--n-equation-points", type=int, default=100000)
    p.add_argument("--batch-size-data", type=int, default=512)
    p.add_argument("--batch-size-equation", type=int, default=2048)
    p.add_argument("--validation-batch-size", type=int, default=20000)
    p.add_argument(
        "--learning-rate",
        type=float,
        default=DEFAULT_TRAINING["learning_rate"],
    )
    p.add_argument("--data-loss-weight", type=float, default=10.0)
    p.add_argument("--equation-loss-weight", type=float, default=1.0)
    p.add_argument("--seed", type=int, default=2025)
    p.add_argument(
        "--diagnostic-interval",
        type=int,
        default=50,
        help="Evaluate the fixed validation set every N epochs; 0 disables intermediate validation.",
    )
    p.add_argument("--resume", action="store_true")
    return p.parse_args()


def ratio_to_key(ratio: float) -> Tuple[int, str]:
    pct = int(round(float(ratio) * 100.0))
    if pct not in (1, 2, 3, 4, 5) or not np.isclose(ratio, pct / 100.0):
        raise ValueError(
            "--supervised-ratio must be one of 0.01, 0.02, 0.03, 0.04, 0.05"
        )
    return pct, f"train_{pct}pct"


def load_protocol(protocol_root: Path, ratio: float, n_equation_points: int):
    idx_path = protocol_root / "protocol_indices.npz"
    eq_path = protocol_root / "collocation_points.csv"
    summary_path = protocol_root / "protocol_summary.csv"

    for path in (idx_path, eq_path, summary_path):
        if not path.exists():
            raise FileNotFoundError(f"Missing protocol artifact: {path}")

    pct, train_key = ratio_to_key(ratio)
    arrays = np.load(idx_path)

    if train_key not in arrays.files:
        raise KeyError(f"Protocol has no key {train_key}. Available: {arrays.files}")

    train_idx = np.asarray(arrays[train_key], dtype=np.int64)
    val_idx = np.asarray(arrays["validation_indices"], dtype=np.int64)
    test_idx = np.asarray(arrays["test_indices"], dtype=np.int64)

    # Strict overlap checks.
    if np.intersect1d(train_idx, val_idx).size:
        raise RuntimeError("Supervised training set overlaps validation set.")
    if np.intersect1d(train_idx, test_idx).size:
        raise RuntimeError("Supervised training set overlaps held-out test set.")
    if np.intersect1d(val_idx, test_idx).size:
        raise RuntimeError("Validation set overlaps held-out test set.")

    summary = pd.read_csv(summary_path).iloc[0]
    n_total = int(summary["total_reference_points"])
    expected = int(round(n_total * ratio))
    if len(train_idx) != expected:
        raise RuntimeError(
            f"{pct}% training set has {len(train_idx)} points; expected {expected}."
        )

    if "flat_index_order" in summary.index:
        order = str(summary["flat_index_order"])
        if "time_major" not in order:
            raise RuntimeError(
                f"Unexpected protocol flattening convention: {order}"
            )

    eq_df = pd.read_csv(eq_path)
    required = ["x", "y", "t"]
    if not all(c in eq_df.columns for c in required):
        raise ValueError(f"{eq_path} must contain columns {required}")

    if n_equation_points < 1:
        raise ValueError("--n-equation-points must be >= 1")
    if n_equation_points > len(eq_df):
        raise ValueError(
            f"Requested {n_equation_points} equation points, but protocol stores {len(eq_df)}."
        )

    # Deterministic prefix of the fixed protocol collocation file.
    eq = eq_df.loc[: n_equation_points - 1, required].to_numpy(
        dtype=np.float32
    )

    return train_idx, val_idx, test_idx, eq, summary


def load_reference_stack(data_path: Path) -> torch.Tensor:
    x, y, t, u, v, p, _ = read_2D_data(str(data_path))
    data = torch.cat([x, y, t, u, v, p], dim=1).float()
    return data


def load_checkpoint_if_requested(
    model: torch.nn.Module,
    checkpoint: Path,
    device: torch.device,
    resume: bool,
) -> None:
    if not resume:
        return
    if not checkpoint.exists():
        print(f"[resume] checkpoint does not exist; training from scratch: {checkpoint}")
        return

    try:
        state = torch.load(checkpoint, map_location=device, weights_only=True)
    except TypeError:
        state = torch.load(checkpoint, map_location=device)

    model.load_state_dict(state, strict=True)
    print(f"[resume] loaded: {checkpoint}")


def compute_total_loss(
    data_loss: torch.Tensor,
    equation_loss: torch.Tensor,
    adaptive_loss: torch.Tensor | None,
    data_loss_weight: float,
    equation_loss_weight: float,
) -> torch.Tensor:
    wd = float(data_loss_weight) * data_loss
    we = float(equation_loss_weight) * equation_loss

    if adaptive_loss is None:
        return wd + we

    # This is a pair of GLOBAL trainable log-loss scales, not pointwise
    # self-adaptive weighting.
    return (
        torch.exp(-adaptive_loss[0]) * wd
        + torch.exp(-adaptive_loss[1]) * we
        + adaptive_loss.sum()
    )


def batch_slice_with_wrap(
    tensor: torch.Tensor,
    start: int,
    batch_size: int,
) -> torch.Tensor:
    """Return a full batch, wrapping around deterministically if needed."""
    n = len(tensor)
    if n == 0:
        raise ValueError("Cannot batch an empty tensor.")

    start = start % n
    end = start + batch_size

    if end <= n:
        return tensor[start:end]

    first = tensor[start:n]
    second = tensor[0 : end - n]
    return torch.cat([first, second], dim=0)


def evaluate_validation(
    model: torch.nn.Module,
    validation_data: torch.Tensor,
    device: torch.device,
    batch_size: int,
) -> Dict[str, float]:
    """Evaluate the fixed validation labels only; no held-out-test access."""
    was_training = model.training
    model.eval()

    pred_u = []
    pred_v = []
    pred_p = []
    ref_u = []
    ref_v = []
    ref_p = []

    for start in range(0, len(validation_data), batch_size):
        batch = validation_data[start : start + batch_size]
        x = batch[:, 0:1].to(device)
        y = batch[:, 1:2].to(device)
        t = batch[:, 2:3].to(device)

        u, v, p = model.predict_fields_safe(
            x, y, t,
            create_graph=False,
            train_mode=False,
        )

        pred_u.append(u.detach().cpu())
        pred_v.append(v.detach().cpu())
        pred_p.append(p.detach().cpu())

        ref_u.append(batch[:, 3:4].cpu())
        ref_v.append(batch[:, 4:5].cpu())
        ref_p.append(batch[:, 5:6].cpu())

    pu = torch.cat(pred_u).numpy().reshape(-1)
    pv = torch.cat(pred_v).numpy().reshape(-1)
    pp = torch.cat(pred_p).numpy().reshape(-1)

    ru = torch.cat(ref_u).numpy().reshape(-1)
    rv = torch.cat(ref_v).numpy().reshape(-1)
    rp = torch.cat(ref_p).numpy().reshape(-1)

    def metrics(pred, ref, prefix):
        err = pred - ref
        rmse = float(np.sqrt(np.mean(err**2)))
        mae = float(np.mean(np.abs(err)))
        denom = float(np.linalg.norm(ref))
        rel_l2 = float(np.linalg.norm(err) / max(denom, 1e-12))
        return {
            f"val_{prefix}_rmse": rmse,
            f"val_{prefix}_mae": mae,
            f"val_{prefix}_relative_l2": rel_l2,
        }

    out = {}
    out.update(metrics(pu, ru, "u"))
    out.update(metrics(pv, rv, "v"))
    out.update(metrics(pp, rp, "p"))

    # Velocity-only aggregate is useful for model selection without letting
    # pressure-gauge sensitivity dominate.
    out["val_uv_rmse_mean"] = 0.5 * (
        out["val_u_rmse"] + out["val_v_rmse"]
    )

    if was_training:
        model.train()

    return out


def train(args: argparse.Namespace) -> None:
    set_seed(args.seed)
    device = get_device()

    data_path = Path(args.data_path)
    protocol_root = Path(args.protocol_root)
    results_root = Path(args.results_root)
    models_dir = results_root / "models"
    logs_dir = results_root / "training_logs"
    models_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    train_idx, val_idx, test_idx, eq_np, protocol_summary = load_protocol(
        protocol_root=protocol_root,
        ratio=args.supervised_ratio,
        n_equation_points=args.n_equation_points,
    )

    full_data = load_reference_stack(data_path)

    if int(full_data.shape[0]) != int(protocol_summary["total_reference_points"]):
        raise RuntimeError(
            "Reference-data size does not match the protocol."
        )

    train_data = full_data[torch.from_numpy(train_idx)]
    validation_data = full_data[torch.from_numpy(val_idx)]

    # Deliberately do not construct held-out test labels for training/model selection.
    del test_idx

    equation_points = torch.tensor(eq_np, dtype=torch.float32)

    cfg = dict(METHODS[args.method])
    cfg["checkpoint"] = models_dir / f"{args.method}.pth"

    model = build_model(cfg, LAYER_MAT_PSI).to(device)
    checkpoint = Path(cfg["checkpoint"])
    load_checkpoint_if_requested(model, checkpoint, device, args.resume)

    adaptive_loss = None
    if cfg.get("adaptive_loss", False):
        adaptive_loss = torch.nn.Parameter(torch.zeros(2, device=device))

    optimized_parameters = list(model.parameters())
    if adaptive_loss is not None:
        optimized_parameters.append(adaptive_loss)

    optimizer = torch.optim.Adam(
        optimized_parameters,
        lr=args.learning_rate,
        weight_decay=float(cfg.get("weight_decay", 0.0)),
    )

    scheduler = ChainedScheduler(
        optimizer,
        T_0=DEFAULT_TRAINING["scheduler_T0"],
        T_mul=DEFAULT_TRAINING["scheduler_Tmul"],
        eta_min=0.0,
        gamma=DEFAULT_TRAINING["decay_rate"],
        max_lr=args.learning_rate,
        warmup_steps=DEFAULT_TRAINING["warmup_steps"],
    )

    backbone_params = int(count_parameters(model))
    additional_params = 0 if adaptive_loss is None else int(adaptive_loss.numel())
    total_optimized_params = backbone_params + additional_params

    n_data = len(train_data)
    n_eq = len(equation_points)

    if args.batch_size_data < 1 or args.batch_size_equation < 1:
        raise ValueError("Batch sizes must be >= 1.")

    steps_per_epoch = max(
        math.ceil(n_data / args.batch_size_data),
        math.ceil(n_eq / args.batch_size_equation),
    )

    pct, _ = ratio_to_key(args.supervised_ratio)

    print("=" * 92)
    print("Cylinder revised sparse-data training v2")
    print(f"Method: {args.method} ({cfg.get('label', args.method)})")
    print(f"Device: {device}")
    print(f"Protocol: {protocol_root}")
    print(f"Supervised ratio: {args.supervised_ratio:.2%}")
    print(f"Supervised points: {n_data}")
    print(f"Validation points: {len(validation_data)}")
    print("Held-out test points: RESERVED AND NOT ACCESSED DURING TRAINING")
    print(f"Equation points: {n_eq}")
    print(f"Data batch size: {args.batch_size_data}")
    print(f"Equation batch size: {args.batch_size_equation}")
    print(f"Steps per epoch: {steps_per_epoch}")
    print(f"Backbone parameters: {backbone_params}")
    print(f"Additional trainable parameters: {additional_params}")
    print(f"Total optimized parameters: {total_optimized_params}")
    print(f"Dropout rate: {cfg.get('dropout_rate', 0.0)}")
    print(f"Weight decay: {cfg.get('weight_decay', 0.0)}")
    print(f"Data loss weight: {args.data_loss_weight}")
    print(f"Equation loss weight: {args.equation_loss_weight}")
    print(f"Seed: {args.seed}")
    print("=" * 92)

    rows = []
    validation_rows = []
    start_time = time.perf_counter()

    for epoch in range(1, args.epochs + 1):
        model.train()

        # Deterministic seed stream through torch RNG; same protocol points,
        # new order each epoch.
        data_perm = torch.randperm(n_data)
        eq_perm = torch.randperm(n_eq)
        data_epoch = train_data[data_perm]
        eq_epoch = equation_points[eq_perm]

        total_vals = []
        data_vals = []
        eq_vals = []

        for step in range(steps_per_epoch):
            data_batch = batch_slice_with_wrap(
                data_epoch,
                step * args.batch_size_data,
                args.batch_size_data,
            )
            eq_batch = batch_slice_with_wrap(
                eq_epoch,
                step * args.batch_size_equation,
                args.batch_size_equation,
            )

            x = data_batch[:, 0:1].to(device).detach().clone().requires_grad_(True)
            y = data_batch[:, 1:2].to(device).detach().clone().requires_grad_(True)
            t = data_batch[:, 2:3].to(device).detach().clone().requires_grad_(True)
            u = data_batch[:, 3:4].to(device)
            v = data_batch[:, 4:5].to(device)
            p = data_batch[:, 5:6].to(device)

            xe = eq_batch[:, 0:1].to(device).detach().clone().requires_grad_(True)
            ye = eq_batch[:, 1:2].to(device).detach().clone().requires_grad_(True)
            te = eq_batch[:, 2:3].to(device).detach().clone().requires_grad_(True)

            optimizer.zero_grad(set_to_none=True)

            data_loss = model.data_mse_psi(x, y, t, u, v, p)

            # Important: even if equation-loss weight is zero, compute the
            # residual during screening runs only when needed. For lambda=0,
            # skipping this term makes the run a no-interior-physics control.
            if float(args.equation_loss_weight) == 0.0:
                equation_loss = torch.zeros((), device=device)
            else:
                equation_loss = model.equation_mse_dimensionless_psi(
                    xe, ye, te, Re=REYNOLDS
                )

            total_loss = compute_total_loss(
                data_loss=data_loss,
                equation_loss=equation_loss,
                adaptive_loss=adaptive_loss,
                data_loss_weight=args.data_loss_weight,
                equation_loss_weight=args.equation_loss_weight,
            )

            if not torch.isfinite(total_loss):
                raise FloatingPointError(
                    f"Non-finite loss at epoch={epoch}, step={step+1}: "
                    f"total={float(total_loss.detach().cpu())}, "
                    f"data={float(data_loss.detach().cpu())}, "
                    f"equation={float(equation_loss.detach().cpu())}"
                )

            total_loss.backward()
            torch.nn.utils.clip_grad_norm_(optimized_parameters, max_norm=10.0)
            optimizer.step()

            total_vals.append(float(total_loss.detach().cpu()))
            data_vals.append(float(data_loss.detach().cpu()))
            eq_vals.append(float(equation_loss.detach().cpu()))

        scheduler.step()

        elapsed = time.perf_counter() - start_time

        row = {
            "method": args.method,
            "epoch": epoch,
            "supervised_ratio": args.supervised_ratio,
            "supervised_points": n_data,
            "validation_points": len(validation_data),
            "equation_points": n_eq,
            "batch_size_data": args.batch_size_data,
            "batch_size_equation": args.batch_size_equation,
            "steps_per_epoch": steps_per_epoch,
            "total_loss": float(np.mean(total_vals)),
            "data_loss": float(np.mean(data_vals)),
            "equation_loss": float(np.mean(eq_vals)),
            "weighted_data_loss": float(args.data_loss_weight * np.mean(data_vals)),
            "weighted_equation_loss": float(args.equation_loss_weight * np.mean(eq_vals)),
            "learning_rate": float(optimizer.param_groups[0]["lr"]),
            "elapsed_seconds": elapsed,
            "backbone_parameters": backbone_params,
            "additional_trainable_parameters": additional_params,
            "total_optimized_parameters": total_optimized_params,
            "seed": args.seed,
        }

        if adaptive_loss is not None:
            row["adaptive_log_var_data"] = float(adaptive_loss[0].detach().cpu())
            row["adaptive_log_var_equation"] = float(adaptive_loss[1].detach().cpu())
            row["adaptive_weight_data"] = float(torch.exp(-adaptive_loss[0]).detach().cpu())
            row["adaptive_weight_equation"] = float(torch.exp(-adaptive_loss[1]).detach().cpu())

        rows.append(row)

        should_validate = (
            epoch == args.epochs
            or (
                args.diagnostic_interval > 0
                and epoch % args.diagnostic_interval == 0
            )
        )

        val_text = ""
        if should_validate:
            val = evaluate_validation(
                model=model,
                validation_data=validation_data,
                device=device,
                batch_size=args.validation_batch_size,
            )
            val_row = {
                "method": args.method,
                "epoch": epoch,
                "supervised_ratio": args.supervised_ratio,
                "equation_loss_weight": args.equation_loss_weight,
                "seed": args.seed,
                **val,
            }
            validation_rows.append(val_row)
            val_text = (
                f" | val_u={val['val_u_rmse']:.3e}"
                f" val_v={val['val_v_rmse']:.3e}"
                f" val_p={val['val_p_rmse']:.3e}"
            )

        torch.save(model.state_dict(), checkpoint)

        pd.DataFrame(rows).to_csv(
            logs_dir / f"{args.method}_training_log.csv",
            index=False,
        )
        if validation_rows:
            pd.DataFrame(validation_rows).to_csv(
                logs_dir / f"{args.method}_validation_log.csv",
                index=False,
            )

        print(
            f"[{args.method}] epoch {epoch:05d}/{args.epochs}"
            f" | total={row['total_loss']:.4e}"
            f" | data={row['data_loss']:.4e}"
            f" | eq={row['equation_loss']:.4e}"
            f" | lr={row['learning_rate']:.2e}"
            f" | time={elapsed:.1f}s"
            f"{val_text}"
        )

    final_val = evaluate_validation(
        model=model,
        validation_data=validation_data,
        device=device,
        batch_size=args.validation_batch_size,
    )

    total_time = time.perf_counter() - start_time

    summary = {
        "protocol_version": str(protocol_summary["protocol_version"]),
        "method": args.method,
        "label": cfg.get("label", args.method),
        "checkpoint": str(checkpoint),
        "epochs": args.epochs,
        "supervised_ratio": args.supervised_ratio,
        "supervised_points": n_data,
        "validation_points": len(validation_data),
        "heldout_test_accessed_during_training": False,
        "equation_points": n_eq,
        "batch_size_data": args.batch_size_data,
        "batch_size_equation": args.batch_size_equation,
        "steps_per_epoch": steps_per_epoch,
        "learning_rate_initial": args.learning_rate,
        "data_loss_weight": args.data_loss_weight,
        "equation_loss_weight": args.equation_loss_weight,
        "dropout_rate": cfg.get("dropout_rate", 0.0),
        "weight_decay": cfg.get("weight_decay", 0.0),
        "adaptive_loss": cfg.get("adaptive_loss", False),
        "backbone_parameters": backbone_params,
        "additional_trainable_parameters": additional_params,
        "total_optimized_parameters": total_optimized_params,
        "training_time_seconds": total_time,
        "final_total_loss": rows[-1]["total_loss"],
        "final_data_loss": rows[-1]["data_loss"],
        "final_equation_loss": rows[-1]["equation_loss"],
        "seed": args.seed,
        **final_val,
    }

    if adaptive_loss is not None:
        summary["final_adaptive_log_var_data"] = float(adaptive_loss[0].detach().cpu())
        summary["final_adaptive_log_var_equation"] = float(adaptive_loss[1].detach().cpu())
        summary["final_adaptive_weight_data"] = float(torch.exp(-adaptive_loss[0]).detach().cpu())
        summary["final_adaptive_weight_equation"] = float(torch.exp(-adaptive_loss[1]).detach().cpu())

    pd.DataFrame([summary]).to_csv(
        logs_dir / f"{args.method}_training_summary.csv",
        index=False,
    )

    print("\nTraining complete.")
    print(f"Checkpoint: {checkpoint}")
    print(
        "Training summary:",
        logs_dir / f"{args.method}_training_summary.csv",
    )
    print("Held-out test set was not accessed.")


def main():
    args = parse_args()

    if not any(np.isclose(args.supervised_ratio, r) for r in ALLOWED_RATIOS):
        raise ValueError(
            f"--supervised-ratio must be one of {ALLOWED_RATIOS}"
        )
    if args.epochs < 1:
        raise ValueError("--epochs must be >= 1")
    if args.validation_batch_size < 1:
        raise ValueError("--validation-batch-size must be >= 1")

    train(args)


if __name__ == "__main__":
    main()
